
development:
  adapter: postgresql
  encoding: unicode
  database: pubcrawl_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: pubcrawl_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: pubcrawl_production
  pool: 5
