# RED LINE STATIONS
Station.create(name:'Alewife', lat: 42.395588, long: -71.141948, last_train_nb: nil,last_train_sb: Chronic.parse("0:22 am"), line: 'red', nb_endpoint: true, sb_endpoint: false, mbta_id: "Alewife")
Station.create(name:'Davis', lat: 42.396197, long: -71.121926, last_train_nb: Chronic.parse("1:15 am") ,last_train_sb: Chronic.parse("0:25 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Davis")
Station.create(name:'Porter', lat: 42.388505, long: -71.119148, last_train_nb: Chronic.parse("1:12 am"),last_train_sb: Chronic.parse("0:28 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Porter Square")
Station.create(name:'Harvard', lat: 42.373653, long: -71.118954, last_train_nb: Chronic.parse("1:09, am"),last_train_sb: Chronic.parse("0:31 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Harvard Square")
Station.create(name:'Central', lat: 42.365603, long: -71.104031, last_train_nb: Chronic.parse("1:06 am"),last_train_sb: Chronic.parse("0:34 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Central Square")
Station.create(name:'Kendall/MIT', lat: 42.362413, long: -71.086382, last_train_nb: Chronic.parse("1:03 am"),last_train_sb: Chronic.parse("0:37 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Kendall/MIT")
Station.create(name:'Charles/MGH', lat: 42.361255, long: -71.070825, last_train_nb: Chronic.parse("1:00 am"),last_train_sb: Chronic.parse("0:40 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Charles/MGH")
Station.create(name:'Park St', lat: 42.356332, long: -71.061952, last_train_nb: Chronic.parse("0:57 am"),last_train_sb: Chronic.parse("0:43 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Park Street")
Station.create(name:'Downtown Crossing', lat: 42.355515, long: -71.060493, last_train_nb: Chronic.parse("0:54 am"), last_train_sb: Chronic.parse("0:46 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Downtown Crossing")
Station.create(name:'South Station', lat: 42.351971, long: -71.056008, last_train_nb: Chronic.parse("0:51 am"),last_train_sb: Chronic.parse("0:49 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "South Station")
Station.create(name:'Broadway', lat: 42.342884, long: -71.057349, last_train_nb: Chronic.parse("0:48 am"),last_train_sb: Chronic.parse("0:52 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Broadway")
Station.create(name:'Andrew', lat: 42.329362, long: -71.056845, last_train_nb: Chronic.parse("0:45 am"),last_train_sb: Chronic.parse("0:55 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Andrew")
Station.create(name:'JFK/UMass', lat: 42.320732, long: -71.051717, last_train_nb: Chronic.parse("0:42 am"),last_train_sb: Chronic.parse("0:58 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "JFK/UMass")
Station.create(name:'Savin Hill', lat: 42.312672, long: -71.052747, last_train_nb: Chronic.parse("0:39 am"),last_train_sb: Chronic.parse("1:01 am"), line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Savin Hill")
Station.create(name:'Fields Corner', lat: 42.300175, long: -71.061561, last_train_nb: Chronic.parse("0:36 am") , last_train_sb: Chronic.parse("1:04 am") , line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Fields Corner")
Station.create(name:'Shawmut', lat: 42.293136, long: -71.065649, last_train_nb: Chronic.parse("0:33 am") , last_train_sb: Chronic.parse("1:07 am") , line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Shawmut")
Station.create(name:'Ashmont', lat: 42.284675, long: -71.064571, last_train_nb: Chronic.parse("0:30 am") , last_train_sb: nil , line: 'red', nb_endpoint: false, sb_endpoint: true, mbta_id: "Ashmont")
Station.create(name:'North Quincy', lat: 42.275233, long: -71.029504, last_train_nb: Chronic.parse("0:30 am") , last_train_sb: Chronic.parse("1:10 am") , line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "North Quincy")
Station.create(name:'Wollaston', lat: 42.266472, long: -71.020288, last_train_nb: Chronic.parse("0:27 am") , last_train_sb: Chronic.parse("1:04 am") , line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Wollaston")
Station.create(name:'Quincy Center', lat: 42.251727, long: -71.005358, last_train_nb: Chronic.parse("0:24 am") , last_train_sb: Chronic.parse("1:07") , line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Quincy Center")
Station.create(name:'Quincy Adams', lat: 42.233331, long: -71.006979, last_train_nb: Chronic.parse("0:21 am") , last_train_sb: Chronic.parse("1:10 am") , line: 'red', nb_endpoint: false, sb_endpoint: false, mbta_id: "Quincy Adams")
Station.create(name:'Braintree', lat: 42.207835, long: -71.001029, last_train_nb: Chronic.parse("0:18 am") , last_train_sb: nil , line: 'red', nb_endpoint: false, sb_endpoint: true, mbta_id: "Braintree")

# ORANGE LINE STATIONS
Station.create(name:'Oak Grove', lat: 42.435145, long:-71.071672, last_train_nb: nil, last_train_sb: Chronic.parse("0:30am") , line: 'orange', nb_endpoint: true, sb_endpoint: false, mbta_id: "Oak Grove")
Station.create(name:'Malden Center', lat: 42.251727, long: -71.073754, last_train_nb: Chronic.parse("1:26am") , last_train_sb: Chronic.parse("0:34am") , line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Malden Center")
Station.create(name:'Wellington', lat: 42.404256, long: -71.081221, last_train_nb: Chronic.parse("1:23am") , last_train_sb: Chronic.parse("0:38am") , line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Wellington")
Station.create(name:'Sullivan Square', lat: 42.384146, long: -71.077058, last_train_nb: Chronic.parse("1:20am") , last_train_sb: Chronic.parse("0:42am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Sullivan")
Station.create(name:'Community College', lat: 42.373653, long: -71.069745, last_train_nb: Chronic.parse("1:17am"), last_train_sb: Chronic.parse("0:46am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Community College")
Station.create(name:'North Station', lat: 42.365607, long: -71.061341, last_train_nb: Chronic.parse("1:14am"), last_train_sb: Chronic.parse("0:50am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "North Station")
Station.create(name:'Haymarket', lat: 42.363015, long: -71.058225, last_train_nb: Chronic.parse("1:11am"), last_train_sb: Chronic.parse("0:54am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Haymarket")
Station.create(name:'State', lat: 42.35898, long: -71.057554, last_train_nb: Chronic.parse("1:08am"), last_train_sb: Chronic.parse("0:58am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "State Street")
Station.create(name:'Downtown Crossing', lat: 42.355515, long: -71.060239, last_train_nb: Chronic.parse("1:05am"), last_train_sb: Chronic.parse("1:02am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Downtown Crossing")
Station.create(name:'Chinatown', lat: 42.35261, long: -71.06287, last_train_nb: Chronic.parse("1:02am"), last_train_sb: Chronic.parse("1:06am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Chinatown")
Station.create(name:'Tufts Medical Center', lat: 42.349656, long: -71.063868, last_train_nb: Chronic.parse("0:59am"), last_train_sb: Chronic.parse("1:10am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Tufts Medical")
Station.create(name:'Back Bay', lat: 42.347285, long: -71.075774, last_train_nb: Chronic.parse("0:56am"), last_train_sb: Chronic.parse("1:14am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Back Bay")
Station.create(name:'Massachusetts Ave', lat: 42.341211, long: -71.083671, last_train_nb: Chronic.parse("0:53am"), last_train_sb: Chronic.parse("1:17am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Mass Ave")
Station.create(name:'Ruggles', lat: 42.336373, long: -71.088799, last_train_nb: Chronic.parse("0:50am"), last_train_sb: Chronic.parse("1:21am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Ruggles")
Station.create(name:'Roxbury Crossing', lat: 42.331345, long: -71.095387, last_train_nb: Chronic.parse("0:47am"), last_train_sb: Chronic.parse("1:25am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Roxbury Crossing")
Station.create(name:'Jackson Square', lat: 42.323135, long: -71.099494, last_train_nb: Chronic.parse("0:44am"), last_train_sb: Chronic.parse("1:29am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Jackson Square")
Station.create(name:'Stony Brook', lat: 42.317099, long: -71.104163, last_train_nb: Chronic.parse("0:41am"), last_train_sb: Chronic.parse("1:33am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Stony Brook")
Station.create(name:'Green Street', lat: 42.310498, long: -71.107403, last_train_nb: Chronic.parse("0:38am"), last_train_sb: Chronic.parse("1:37am"), line: 'orange', nb_endpoint: false, sb_endpoint: false, mbta_id: "Green Street")
Station.create(name:'Forest Hills', lat: 42.300516, long: -71.113432, last_train_nb: Chronic.parse("0:35am"), last_train_sb: nil, line: 'orange', nb_endpoint: false, sb_endpoint: true, mbta_id: "Forest Hills")

# GREEN LINE STATIONS
Station.create(name:'Lechmere', lat: 42.370784, long: -71.076568, last_train_nb: nil, last_train_sb: Chronic.parse("0:30am"), line: 'green', nb_endpoint: true, sb_endpoint: false, mbta_id: "")
Station.create(name:'Science Park', lat: 42.366757, long: -71.067835, last_train_nb: Chronic.parse("1:31am"), last_train_sb: Chronic.parse("0:32am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'North Station', lat: 42.370784, long: -71.076568, last_train_nb: Chronic.parse("1:28am"), last_train_sb: Chronic.parse("0:35am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Haymarket', lat: 42.363015, long: -71.058225, last_train_nb: Chronic.parse("1:25am"), last_train_sb: Chronic.parse("0:38am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Government Center', lat: 42.359971, long: -71.059595, last_train_nb: Chronic.parse("1:22am") , last_train_sb: Chronic.parse("0:42am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Park Street', lat: 42.356332, long: -71.061952, last_train_nb: Chronic.parse("1:19am"), last_train_sb: Chronic.parse("0:45am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Boylston Street', lat: 42.35301, long: -71.064552, last_train_nb: Chronic.parse("1:16am"), last_train_sb: Chronic.parse("0:48am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Arlington', lat: 42.3519, long: -71.070903, last_train_nb: Chronic.parse("1:13am"), last_train_sb: Chronic.parse("0:51am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Copley', lat: 42.350068, long: -71.077339, last_train_nb: Chronic.parse("1:10am"), last_train_sb: Chronic.parse("0:54am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Hynes Convention Center', lat: 42.347904, long: -71.087855, last_train_nb: Chronic.parse("1:07am"), last_train_sb: Chronic.parse("0:57am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Kenmore', lat: 42.348911, long: -71.095095, last_train_nb: Chronic.parse("1:04am"), last_train_sb: Chronic.parse("1:00am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")

# The B Line
Station.create(name:'Blandford Street', lat: 42.349323, long: -71.10032, last_train_nb: Chronic.parse("1:01am"), last_train_sb: Chronic.parse("1:03am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Boston University East', lat: 42.349727, long: -71.103882, last_train_nb: Chronic.parse("0:58am"), last_train_sb: Chronic.parse("1:06am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Boston University Central', lat: 42.3501, long: -71.106843, last_train_nb: Chronic.parse("0:55am"), last_train_sb: Chronic.parse("1:09am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Boston University West', lat: 42.350941, long: -71.11386, last_train_nb: Chronic.parse("0:52am"), last_train_sb: Chronic.parse("1:12am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'St. Paul Street', lat: 42.350925, long: -71.116102, last_train_nb: Chronic.parse("0:49am"), last_train_sb: Chronic.parse("1:15am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Pleasant Street', lat: 42.351488, long: -71.118817, last_train_nb: Chronic.parse("0:46am"), last_train_sb: Chronic.parse("1:18am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Babcock Street', lat: 42.351821, long: -71.121649, last_train_nb: Chronic.parse("0:43am"), last_train_sb: Chronic.parse("1:21am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Packards Corner', lat: 42.351955, long: -71.125007, last_train_nb: Chronic.parse("0:40am"), last_train_sb: Chronic.parse("1:24am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Harvard Avenue', lat: 42.350203, long: -71.13138, last_train_nb: Chronic.parse("0:37am"), last_train_sb: Chronic.parse("1:27am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Griggs Street/Long Avenue', lat: 42.348387, long: -71.134931, last_train_nb: Chronic.parse("0:34am"), last_train_sb: Chronic.parse("1:30am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Allston Street', lat: 42.348839, long: -71.13771, last_train_nb: Chronic.parse("0:31am"), last_train_sb: Chronic.parse("1:33am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Warren Street', lat: 42.348356, long: -71.140414, last_train_nb: Chronic.parse("0:28am"), last_train_sb: Chronic.parse("1:36am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Washington Street', lat: 42.343852, long: -71.142838, last_train_nb: Chronic.parse("0:25am"), last_train_sb: Chronic.parse("1:39am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Sutherland Street', lat: 42.341607, long: -71.146197, last_train_nb: Chronic.parse("0:22am"), last_train_sb: Chronic.parse("1:42am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Chiswick Road Station', lat: 42.341013, long: -71.150703, last_train_nb: Chronic.parse("0:19am"), last_train_sb: Chronic.parse("1:45am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Chestnut Hill Avenue', lat: 42.338419, long: -71.153117, last_train_nb: Chronic.parse("0:16am"), last_train_sb: Chronic.parse("1:48am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'South Street', lat: 42.339768, long: -71.157408, last_train_nb: Chronic.parse("0:13am"), last_train_sb: Chronic.parse("1:51am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Boston College', lat: 42.340037, long: -71.166798, last_train_nb: Chronic.parse("0:10am"), last_train_sb: Chronic.parse("1:54am"), line: 'green', nb_endpoint: false, sb_endpoint: true, mbta_id: "")

# The C Line
Station.create(name:'St Mary\'s Street', lat: 42.345937, long: -71.107296, last_train_nb: Chronic.parse("0:46am"), last_train_sb: Chronic.parse("1:03am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Hawes Street', lat: 42.345192, long: -71.111523, last_train_nb: Chronic.parse("0:43am"), last_train_sb: Chronic.parse("1:06am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Kent Street', lat: 42.344097, long: -71.114141, last_train_nb: Chronic.parse("0:40am"), last_train_sb: Chronic.parse("1:09am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'St Paul Street', lat: 42.343352, long: -71.116973, last_train_nb: Chronic.parse("0:37am"), last_train_sb: Chronic.parse("1:12am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Coolidge Corner', lat: 42.34221, long: -71.121243, last_train_nb: Chronic.parse("0:34am"), last_train_sb: Chronic.parse("1:15am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Summit Avenue', lat: 42.341116, long: -71.125556, last_train_nb: Chronic.parse("0:31am"), last_train_sb: Chronic.parse("1:18am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Brandon Hall', lat: 42.339926, long: -71.129161, last_train_nb: Chronic.parse("0:28am"), last_train_sb: Chronic.parse("1:21am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Fairbanks', lat: 42.339736, long: -71.131092, last_train_nb: Chronic.parse("0:25am"), last_train_sb: Chronic.parse("1:24am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Washington Square', lat: 42.339435, long: -71.135319, last_train_nb: Chronic.parse("0:22am"), last_train_sb: Chronic.parse("1:27am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Tappan Street', lat: 42.338419, long: -71.138688, last_train_nb: Chronic.parse("0:19am"), last_train_sb: Chronic.parse("1:30am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Dean Road', lat: 42.337833, long: -71.141885, last_train_nb: Chronic.parse("0:16am"), last_train_sb: Chronic.parse("1:33am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Englewood Avenue', lat: 42.337087, long: -71.145812, last_train_nb: Chronic.parse("0:13am"), last_train_sb: Chronic.parse("1:26am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Cleveland Circle', lat: 42.33612, long: -71.14931, last_train_nb: Chronic.parse("0:10am"), last_train_sb: nil, line: 'green', nb_endpoint: false, sb_endpoint: true, mbta_id: "")

# The D Line
Station.create(name:'Fenway', lat: 42.345366, long: -71.104227, last_train_nb: Chronic.parse("0:41am"), last_train_sb: Chronic.parse("1:03am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Longwood', lat: 42.341132, long: -71.110428, last_train_nb: Chronic.parse("0:38am"), last_train_sb: Chronic.parse("1:06am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Brookline Village', lat: 42.332804, long: -71.116243, last_train_nb: Chronic.parse("0:35am"), last_train_sb: Chronic.parse("1:09am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Brookline Hills', lat: 42.331313, long: -71.126972, last_train_nb: Chronic.parse("0:32am"), last_train_sb: Chronic.parse("1:12am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Beaconsfield', lat: 42.335882, long: -71.140769, last_train_nb: Chronic.parse("0:29am"), last_train_sb: Chronic.parse("1:15am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Reservoir', lat: 42.335326, long: -71.149353, last_train_nb: Chronic.parse("0:26am"), last_train_sb: Chronic.parse("1:18am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Chestnut Hill', lat: 42.326665, long: -71.165317, last_train_nb: Chronic.parse("0:23am"), last_train_sb: Chronic.parse("1:21am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Newton Centre', lat: 42.329378, long: -71.192354, last_train_nb: Chronic.parse("0:20am"), last_train_sb: Chronic.parse("1:24am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Newton Highlands', lat: 42.321716, long: -71.206087, last_train_nb: Chronic.parse("0:17am"), last_train_sb: Chronic.parse("1:27am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Eliot', lat: 42.318939, long: -71.21673, last_train_nb: Chronic.parse("0:14am"), last_train_sb: Chronic.parse("1:30am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Waban', lat: 42.325936, long: -71.230742, last_train_nb: Chronic.parse("0:11am"), last_train_sb: Chronic.parse("1:33am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Woodland', lat: 42.333407, long: -71.244346, last_train_nb: Chronic.parse("0:08am"), last_train_sb: Chronic.parse("1:36am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Riverside', lat: 42.337119, long: -71.251277, last_train_nb: Chronic.parse("0:05am"), last_train_sb: Chronic.parse("1:39am"), line: 'green', nb_endpoint: false, sb_endpoint: true, mbta_id: "")

# The E Line
Station.create(name:'Prudential', lat: 42.345572, long: -71.081675, last_train_nb: Chronic.parse("1:17am"), last_train_sb: Chronic.parse("0:54am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Symphony', lat: 42.342686, long: -71.085022, last_train_nb: Chronic.parse("1:14am"), last_train_sb: Chronic.parse("0:57am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Northeastern', lat: 42.340386, long: -71.088799, last_train_nb: Chronic.parse("1:11am"), last_train_sb: Chronic.parse("1:00am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Museum of Fine Arts', lat: 42.33769, long: -71.095494, last_train_nb: Chronic.parse("1:08am"), last_train_sb: Chronic.parse("1:03am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Longwood Medical Area', lat: 42.335961, long: -71.100086, last_train_nb: Chronic.parse("1:05am"), last_train_sb: Chronic.parse("1:06am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Brigham Circle', lat: 42.334184, long: -71.104635, last_train_nb: Chronic.parse("1:02am"), last_train_sb: Chronic.parse("1:09am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Fenwood Road', lat: 42.333756, long: -71.105686, last_train_nb: Chronic.parse("0:59am"), last_train_sb: Chronic.parse("1:12am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Mission Park', lat: 42.333201, long: -71.109677, last_train_nb: Chronic.parse("0:56am"), last_train_sb: Chronic.parse("1:15am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Riverway', lat: 42.331726, long: -71.111909, last_train_nb: Chronic.parse("0:53am"), last_train_sb: Chronic.parse("1:18am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Back of the Hill', lat: 42.330155, long: -71.111308, last_train_nb: Chronic.parse("0:50am"), last_train_sb: Chronic.parse("1:21am"), line: 'green', nb_endpoint: false, sb_endpoint: false, mbta_id: "")
Station.create(name:'Heath Street', lat: 42.328918, long: -71.110493, last_train_nb: Chronic.parse("0:47am"), last_train_sb: Chronic.parse("1:24am,"), line: 'green', nb_endpoint: false, sb_endpoint: true, mbta_id: "")

# BLUE LINE STATIONS
Station.create(name:'Wonderland', lat: 42.413382, long: -70.991617, last_train_nb: nil, last_train_sb: Chronic.parse("0:26am"), line: 'blue', nb_endpoint: true, sb_endpoint: false, mbta_id: "Wonderland")
Station.create(name:'Revere Beach', lat: 42.407837, long: -70.99254, last_train_nb: Chronic.parse("1:27am"), last_train_sb: Chronic.parse("0:29am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Revere Beach")
Station.create(name:'Beachmont', lat: 42.397553, long: -70.992282, last_train_nb: Chronic.parse("1:24am"), last_train_sb: Chronic.parse("0:32am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Beachmont")
Station.create(name:'Suffolk Downs', lat: 42.390771, long: -70.997132, last_train_nb: Chronic.parse("1:21am"), last_train_sb: Chronic.parse("0:35am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Suffolk Downs")
Station.create(name:'Orient Heights', lat: 42.387094, long: -71.004728, last_train_nb: Chronic.parse("1:18am"), last_train_sb: Chronic.parse("0:38am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Orient Heights")
Station.create(name:'Wood Island', lat: 42.379661, long: -71.022538, last_train_nb: Chronic.parse("1:15am"), last_train_sb: Chronic.parse("0:41am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Wood Island")
Station.create(name:'Airport', lat: 42.374255, long: -71.030327, last_train_nb: Chronic.parse("1:12am"), last_train_sb: Chronic.parse("0:44am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Airport")
Station.create(name:'Maverick', lat: 42.369071, long: -71.039493, last_train_nb: Chronic.parse("1:09am"), last_train_sb: Chronic.parse("0:47am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Maverick")
Station.create(name:'Aquarium', lat: 42.359812, long: -71.051552, last_train_nb: Chronic.parse("1:06am"), last_train_sb: Chronic.parse("0:50am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Aquarium")
Station.create(name:'State Street', lat: 42.358964, long: -71.057491, last_train_nb: Chronic.parse("1:03am"), last_train_sb: Chronic.parse("0:53am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "State Street")
Station.create(name:'Government Center', lat: 42.359709, long: -71.059111, last_train_nb: Chronic.parse("1:00am"), last_train_sb: Chronic.parse("0:56am"), line: 'blue', nb_endpoint: false, sb_endpoint: false, mbta_id: "Government Center")
Station.create(name:'Bowdoin', lat: 42.361382, long: -71.06204, last_train_nb: Chronic.parse("0:30am"), last_train_sb: nil, line: 'blue', nb_endpoint: false, sb_endpoint: true, mbta_id: "Bowdoin")
